AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple backend for counting visitors

Resources:
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Events:
        VisitorCount:
          Type: Api
          Properties:
            Path: /count
            Method: GET
            RestApiId: !Ref VisitorCounterApi
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:UpdateItem'
                - 'dynamodb:GetItem'
              Resource: !GetAtt ResumeVisitorCount.Arn

  VisitorCounterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  ResumeVisitorCount:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ResumeVisitorCount
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
