AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application.

Globals:
  Function:
    Timeout: 3

Resources:
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Events:
        Count:
          Type: Api
          Properties:
            Path: /count
            Method: GET
      Environment:
        Variables:
          TABLE_NAME: ResumeVisitorCount
