AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application.

Globals:
  Function:
    Timeout: 3

Resources:
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Events:
        Count:
          Type: HttpApi
          Properties:
            ApiId: d7tqrxj7v4
            Path: /count
            Method: GET
      Environment:
        Variables:
          TABLE_NAME: ResumeVisitorCount

  ResumeVisitorCountTablePermission:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ResumeVisitorCountTablePermission
      Roles:
        - !Ref VisitorCounterFunctionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
            Resource: !Sub "arn:aws:dynamodb:us-east-1:${AWS::AccountId}:table/ResumeVisitorCount"
