AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application.

Globals:
  Function:
    Timeout: 3

Resources:
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Events:
        Count:
          Type: HttpApi
          Properties:
            Path: /count
            Method: GET
            ApiId: !Ref ResumeVisitorCountAPI
      Environment:
        Variables:
          TABLE_NAME: ResumeVisitorCount
      Role: !GetAtt LambdaExecutionRole.Arn

  ResumeVisitorCountAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      ApiId: d7tqrxj7v4
      CorsConfiguration:
        AllowMethods:
          - GET
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
          - X-Amz-User-Agent
        AllowOrigins:
          - '*'

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !Sub "arn:aws:dynamodb:us-east-1:${AWS::AccountId}:table/ResumeVisitorCount"
