name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Frontend to S3
      run: |
        aws s3 cp ./frontend/index.html s3://saadmalikresume/index.html --exclude '.git/*' --exclude '.github/*'
        aws s3 cp ./frontend/styles.css s3://saadmalikresume/styles.css --exclude '.git/*' --exclude '.github/*'

  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3.8-venv

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Build and Deploy Backend
      run: |
        cd backend
        sam build
        sam deploy --stack-name resume-visitor-counter --capabilities CAPABILITY_IAM --no-confirm-changeset --region us-east-1 --s3-bucket saadmalikresume

