name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Delete bucket contents
        run: |
          aws s3 rm s3://saadmalikresume/ --recursive

      - name: Deploy to S3
        run: |
          aws s3 cp ./frontend/index.html s3://saadmalikresume/index.html
          aws s3 cp ./frontend/styles.css s3://saadmalikresume/styles.css
          aws s3 cp ./frontend/experience.html s3://saadmalikresume/experience.html
          aws s3 cp ./frontend/education.html s3://saadmalikresume/education.html
          aws s3 cp ./frontend/skills.html s3://saadmalikresume/skills.html
          aws s3 cp ./frontend/contact.html s3://saadmalikresume/contact.html
          aws s3 cp ./frontend/favicon.png s3://saadmalikresume/favicon.png

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E11LQ4C96BKYNW --paths "/*"



#  deploy_backend:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Set up AWS CLI
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
#
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8
#
#      - name: Install dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install software-properties-common
#          sudo add-apt-repository ppa:deadsnakes/ppa
#          sudo apt-get update
#          sudo apt-get install python3.10 python3.10-venv python3.10-distutils
#          python3.10 -m venv venv
#          source venv/bin/activate
#          pip install --upgrade pip
#          pip install aws-sam-cli
#
#      - name: Build and Deploy Backend
#        run: |
#          cd backend
#          sam build
#          sam deploy --stack-name resume-visitor-counter --capabilities CAPABILITY_IAM --no-confirm-changeset --region us-east-1 --resolve-s3
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
